FROM node:6.12.0-alpine AS builder
WORKDIR /app

# add other deps required here such as git~

# copy package.json & package-lock.json
COPY package*.json .
RUN npm i --production && npm cache clean

FROM node:6.12.0-alpine
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

# copy code
COPY . .

# start
# prefer node path-to-app.js
CMD ["npm", "start"]
