FROM node:6.12.0-alpine

WORKDIR /app

# copy package.json & package-lock.json
COPY package*.json yarn.lock ./
RUN yarn install --silent --production && yarn cache clean

# copy code
COPY . .

# start
# prefer node path-to-app.js
CMD ["npm", "start"]
