FROM node:6.12.0-alpine

WORKDIR /app

# copy package.json & package-lock.json
COPY package*.json ./
RUN npm i --production && npm cache clean

# copy code
COPY . .

# start
# prefer node path-to-app.js
CMD npm start
