FROM node:6.12.0-alpine AS builder

WORKDIR /tmp

# add other deps required here such as git~

# copy package.json & package-lock.json
COPY package*.json .
RUN npm i --production && npm cache clean

FROM node:6.12.0-alpine

# copy code
COPY . .
COPY --from=builder /tmp/node_modules ./

# start
CMD npm start
